openapi: 3.0.0
info:
  title: Spotplay
  description: 'Es una plataforma de musica ...'
  contact:
    email: oriamnut09@gmail.com
  licence:
    name: Apache 2.0
    url: http://apac.....
  version: 1.0.0
servers:
- url: http://localhost:4000/api/v1
tags:
- name: Song
  description: canciones de la aplicacion
- name: User
  description: usuarios de la plataforma
- name: Playlist
  description: playlist de usuarios
components:
  schemas:
    Song:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        uri:
          type: string
        duration:
          type: string
        imagen:
          type: string
        idArtist:
          type: integer
          format: int32
        idGender:
          type: integer
          format: int32
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        uri:
          type: string
        duration:
          type: string
        imagen:
          type: string
        idArtist:
          type: integer
          format: int32
        idGender:
          type: integer
          format: int32
paths:
  /user/singup:
    post:
      tags: 
      - User
      summary: create a new user
      operationId: createUser
      description: Se creara un usuario para utilizarlo en la aplicacion
      requestBody: 
        description: Ingrese los datos del usuario a crear
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/xml: 
            schema:
              $ref: '#/components/schemas/User'
        required: true
      response: 
        200:
          description: registro exitoso!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: bad request
          content: {}
        404:
          description: 
          content: {}
  /song:
    get:
      tags:
      - Song
      summary: get all songs
      operationId: get songs
    post:
      tags:
      - Song
      summary: get all users
      operationId: get users
    put:
      tags:
      - Song
      summary: get all users
      operationId: get users
    delete:
      tags:
      - Song
      summary: get all users
      operationId: get users





